export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_FAIL_ACKNOWLEDGED = "USER_LOGIN_FAIL_ACKNOWLED";
export const UPDATE_QUESTIONS_REQUEST = "UPDATE_QUESTIONS_REQUEST";
export const UPDATE_QUESTIONS_SUCCESS = "UPDATE_QUESTIONS_SUCCESS";
export const UPDATE_QUESTIONS_FAIL= "UPDATE_QUESTIONS_FAIL";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_SUCCESS_ACKOWLEDGED = "USER_REGISTER_SUCCESS_ACKOWLEDGED";
export const RESET_ANSWERS_REQUEST = "RESET_ANSWERS_REQUEST";
export const RESET_ANSWERS_SUCCESS = "RESET_ANSWERS_SUCCESS";
export const RESET_ANSWERS_FAIL = "RESET_ANSWERS_FAIL";




